require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Christopher_Burton' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'Christopher_BurtonTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Christopher_Burton-tvOS' do
  # Pods for Christopher_Burton-tvOS

  target 'Christopher_Burton-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
